management:
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include:
            - readinessState
            - db

spring:
  datasource:
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-ce4uca5a499e4m98fgs0-a/sampledb_i8ao

    username: scott
    password: unqnBacdau1KmR9yu4leMAaXd1nOR5dR
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5

mybatis:
  configuration:
    map-underscore-to-camel-case: true
